<?php
/**
 * eKamalia — Installation Wizard
 * Steps: 1 Requirements → 2 Database → 3 Migrate → 4 Admin → 5 Finish
 * After completion a lock file (storage/install.lock) prevents re-running.
 */
declare(strict_types=1);

session_start();
error_reporting(E_ALL);
ini_set('display_errors', '0');

define('EK_ROOT', dirname(__DIR__));
$lockFile  = EK_ROOT . '/storage/install.lock';
$configFile = EK_ROOT . '/config/config.php';

if (is_file($lockFile)) {
    http_response_code(403);
    echo '<!doctype html><meta charset="utf-8"><body style="font-family:sans-serif;text-align:center;padding:80px">'
        . '<h1>🔒 Already Installed</h1><p>eKamalia is installed. For security the installer is locked.</p>'
        . '<p><a href="../">Go to website</a> &nbsp;•&nbsp; <a href="../admin">Admin Panel</a></p>'
        . '<p style="color:#888">To reinstall, delete <code>storage/install.lock</code> via your hosting file manager.</p></body>';
    exit;
}

$slug = function (string $t): string {
    $t = strtolower(trim(preg_replace('~[^\pL\d]+~u', '-', $t), '-'));
    return preg_replace('~-+~', '-', $t) ?: 'item';
};

/* ---------- AJAX actions ---------- */
function json_out(array $data): never {
    echo json_encode($data, JSON_UNESCAPED_UNICODE);
    exit;
}
$do = $_GET['do'] ?? '';
if ($do !== '') {
    header('Content-Type: application/json');
    try {
        switch ($do) {
            case 'requirements':
                $writable = ['storage', 'storage/logs', 'storage/cache', 'storage/backups', 'uploads', 'config'];
                $dirs = [];
                foreach ($writable as $d) {
                    $p = EK_ROOT . '/' . $d;
                    if (!is_dir($p)) @mkdir($p, 0755, true);
                    $dirs[$d] = is_writable($p);
                }
                json_out([
                    'ok' => true,
                    'php_version' => PHP_VERSION,
                    'php_ok' => version_compare(PHP_VERSION, '7.4.0', '>='),
                    'extensions' => [
                        'pdo_mysql' => extension_loaded('pdo_mysql'), 'gd' => extension_loaded('gd'),
                        'mbstring' => extension_loaded('mbstring'), 'curl' => extension_loaded('curl'),
                        'openssl' => extension_loaded('openssl'),
                    ],
                    'dirs' => $dirs,
                ]);

            case 'test_db':
                $h = trim($_POST['host'] ?? 'localhost'); $n = trim($_POST['name'] ?? '');
                $u = trim($_POST['user'] ?? ''); $p = (string)($_POST['pass'] ?? '');
                $dsn = "mysql:host=$h;charset=utf8mb4";
                $pdo = new PDO($dsn, $u, $p, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION, PDO::ATTR_TIMEOUT => 8]);
                // database must exist (hosts like Hostinger pre-create it) — try to create if allowed
                $exists = $pdo->query("SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = " . $pdo->quote($n))->fetch();
                if (!$exists) {
                    try { $pdo->exec("CREATE DATABASE `" . str_replace('`', '', $n) . "` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"); }
                    catch (PDOException $e) { json_out(['ok' => false, 'message' => "Database '$n' does not exist and could not be created. Create it in your hosting panel first."]); }
                }
                $pdo->exec("USE `" . str_replace('`', '', $n) . "`");
                // write config
                $key = bin2hex(random_bytes(32));
                $url = 'http' . (!empty($_SERVER['HTTPS']) ? 's' : '') . '://' . ($_SERVER['HTTP_HOST'] ?? 'localhost');
                $base = rtrim(str_replace('/install', '', dirname($_SERVER['SCRIPT_NAME'] ?? '')), '/');
                if ($base) $url .= $base;
                $cfg = "<?php\n/* eKamalia config — generated by installer " . date('c') . " */\nreturn [\n"
                     . "    'db' => ['host' => " . var_export($h, true) . ", 'name' => " . var_export($n, true) . ", 'user' => " . var_export($u, true) . ", 'pass' => " . var_export($p, true) . ", 'charset' => 'utf8mb4'],\n"
                     . "    'app' => ['url' => " . var_export($url, true) . ", 'key' => " . var_export($key, true) . ", 'timezone' => 'Asia/Karachi', 'env' => 'production', 'version' => '1.0.0'],\n];\n";
                if (!@file_put_contents($configFile, $cfg)) json_out(['ok' => false, 'message' => 'Could not write config/config.php — make the config folder writable.']);
                @chmod($configFile, 0640);
                $_SESSION['install']['db_ok'] = true;
                json_out(['ok' => true, 'message' => 'Connected successfully. Config saved.']);

            case 'migrate':
                if (empty($_SESSION['install']['db_ok'])) json_out(['ok' => false, 'message' => 'Test the database first.']);
                $pdo = ek_installer_db($configFile);
                $sql = file_get_contents(EK_ROOT . '/database/schema.sql');
                foreach (array_filter(array_map('trim', preg_split('/;\s*[\r\n]+/', $sql))) as $stmt) {
                    /* strip leading comment lines so statements following comments still run */
                    $stmt = trim((string)preg_replace('/^(?:[ \t]*--[^\n]*\n)+/', '', $stmt . "\n"));
                    if ($stmt === '' || str_starts_with($stmt, '--')) continue;
                    $pdo->exec($stmt);
                }
                require EK_ROOT . '/database/seed.php';
                ek_seed($pdo);
                json_out(['ok' => true, 'message' => 'All tables created and default data seeded.']);

            case 'admin':
                $name = trim($_POST['name'] ?? ''); $email = trim($_POST['email'] ?? '');
                $pass = (string)($_POST['password'] ?? '');
                if ($name === '' || !filter_var($email, FILTER_VALIDATE_EMAIL)) json_out(['ok' => false, 'message' => 'Valid name and email required.']);
                if (strlen($pass) < 8) json_out(['ok' => false, 'message' => 'Password must be at least 8 characters.']);
                $pdo = ek_installer_db($configFile);
                $st = $pdo->prepare('SELECT id FROM users WHERE email=?'); $st->execute([$email]);
                if ($st->fetch()) json_out(['ok' => false, 'message' => 'This email is already registered.']);
                if (!empty($_POST['demo'])) {
                    require EK_ROOT . '/database/seed.php';   /* provides slugify_s() */
                    require EK_ROOT . '/database/demo.php';
                    ek_seed_demo($pdo);
                }
                $pdo->prepare('INSERT INTO users (name,email,password,role,status,email_verified_at,created_at) VALUES (?,?,?,"admin","active",?,?)')
                    ->execute([$name, $email, password_hash($pass, PASSWORD_DEFAULT), date('Y-m-d H:i:s'), date('Y-m-d H:i:s')]);
                json_out(['ok' => true]);

            case 'finish':
                if (!@file_put_contents($lockFile, 'installed ' . date('c'))) json_out(['ok' => false, 'message' => 'Could not create lock file.']);
                foreach (['storage/logs', 'storage/cache', 'storage/backups'] as $d) @mkdir(EK_ROOT . '/' . $d, 0755, true);
                json_out(['ok' => true]);
        }
        json_out(['ok' => false, 'message' => 'Unknown action']);
    } catch (Throwable $e) {
        json_out(['ok' => false, 'message' => $e->getMessage()]);
    }
}

function ek_installer_db(string $configFile): PDO {
    $c = require $configFile;
    return new PDO(
        "mysql:host={$c['db']['host']};dbname={$c['db']['name']};charset=utf8mb4",
        $c['db']['user'], $c['db']['pass'],
        [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
    );
}

/* default DB values (production credentials supplied by project owner) */
$dHost = 'localhost'; $dName = 'u107154643_kml'; $dUser = 'u107154643_kml1'; $dPass = 'Pakistan7973117';
?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Install eKamalia</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" rel="stylesheet">
<style>
:root{--green:#0B7A3E;--gold:#F0B429;--ink:#0f172a}
body{background:linear-gradient(160deg,#f2f8f4,#e8f2ec 60%,#fdf6e3);min-height:100vh;font-family:system-ui,Segoe UI,sans-serif;color:var(--ink)}
.brand{font-weight:800;font-size:1.5rem;background:linear-gradient(90deg,var(--green),#14915a);-webkit-background-clip:text;background-clip:text;color:transparent}
.card{border:0;border-radius:20px;box-shadow:0 18px 50px rgba(11,122,62,.12)}
.step{width:38px;height:38px;border-radius:50%;display:inline-flex;align-items:center;justify-content:center;font-weight:700;background:#e5ece8;color:#7b8a83;margin-right:8px}
.step.active{background:var(--green);color:#fff}.step.done{background:var(--gold);color:#3d2e00}
.btn-ek{background:linear-gradient(90deg,var(--green),#12905a);color:#fff;border:0;border-radius:12px;padding:.65rem 1.4rem;font-weight:600}
.btn-ek:hover{color:#fff;filter:brightness(1.06)}
.pane{display:none}.pane.active{display:block}
.check{display:flex;justify-content:space-between;padding:.55rem .9rem;border-radius:12px;background:#f6f8f7;margin-bottom:.5rem}
.check .bad{color:#c0392b;font-weight:700}.check .good{color:var(--green);font-weight:700}
code{background:#eef3f0;padding:.1rem .4rem;border-radius:6px}
#console{background:#0d1f16;color:#8fe3b0;font-family:monospace;font-size:.8rem;border-radius:12px;padding:1rem;max-height:180px;overflow:auto;display:none}
</style>
</head>
<body class="py-5">
<div class="container" style="max-width:760px">
  <div class="text-center mb-4">
    <div class="brand"><i class="fa-solid fa-store text-success me-1"></i> eKamalia Installer</div>
    <div class="text-muted small">Kamalia Ka Apna Digital Bazaar — setup wizard</div>
  </div>
  <div class="card p-4 p-md-5">
    <div class="d-flex flex-wrap align-items-center gap-3 mb-4 small">
      <span class="step active" id="dot1">1</span> Requirements
      <i class="fa-solid fa-angle-right text-muted"></i>
      <span class="step" id="dot2">2</span> Database
      <i class="fa-solid fa-angle-right text-muted"></i>
      <span class="step" id="dot3">3</span> Tables &amp; Data
      <i class="fa-solid fa-angle-right text-muted"></i>
      <span class="step" id="dot4">4</span> Admin
      <i class="fa-solid fa-angle-right text-muted"></i>
      <span class="step" id="dot5">5</span> Finish
    </div>

    <div class="pane active" id="pane1">
      <h5 class="fw-bold mb-3">System Requirements</h5>
      <div id="reqBox"><div class="text-muted"><span class="spinner-border spinner-border-sm me-2"></span>Checking your server…</div></div>
      <button class="btn btn-ek mt-3" id="btn1" disabled>Continue <i class="fa-solid fa-arrow-right ms-1"></i></button>
    </div>

    <div class="pane" id="pane2">
      <h5 class="fw-bold mb-3">Database Configuration</h5>
      <p class="text-muted small">Pre-filled with the credentials for ekamalia.com. Edit if different on your server.</p>
      <div class="row g-3">
        <div class="col-md-6"><label class="form-label">DB Host</label><input class="form-control" id="dbHost" value="<?= htmlspecialchars($dHost) ?>"></div>
        <div class="col-md-6"><label class="form-label">Database Name</label><input class="form-control" id="dbName" value="<?= htmlspecialchars($dName) ?>"></div>
        <div class="col-md-6"><label class="form-label">DB Username</label><input class="form-control" id="dbUser" value="<?= htmlspecialchars($dUser) ?>"></div>
        <div class="col-md-6"><label class="form-label">DB Password</label><input class="form-control" type="password" id="dbPass" value="<?= htmlspecialchars($dPass) ?>"></div>
      </div>
      <div id="dbMsg" class="mt-3"></div>
      <button class="btn btn-ek mt-3" id="btn2">Test Connection &amp; Save</button>
    </div>

    <div class="pane" id="pane3">
      <h5 class="fw-bold mb-3">Create Tables &amp; Default Data</h5>
      <p class="text-muted small">This creates all 55+ tables (users, shops, products, ads, orders, payments, POS, bijli feeders…), seeds categories, Kamalia-area cities, pages, sliders and default settings.</p>
      <div id="console"></div>
      <button class="btn btn-ek mt-3" id="btn3">Run Installation <i class="fa-solid fa-database ms-1"></i></button>
    </div>

    <div class="pane" id="pane4">
      <h5 class="fw-bold mb-3">Create Admin Account</h5>
      <div class="row g-3">
        <div class="col-md-6"><label class="form-label">Admin Name</label><input class="form-control" id="adName" placeholder="Your name"></div>
        <div class="col-md-6"><label class="form-label">Admin Email</label><input class="form-control" type="email" id="adEmail" placeholder="admin@ekamalia.com"></div>
        <div class="col-md-6"><label class="form-label">Password (min 8 chars)</label><input class="form-control" type="password" id="adPass"></div>
        <div class="col-md-6"><label class="form-label">Confirm Password</label><input class="form-control" type="password" id="adPass2"></div>
      </div>
      <div class="form-check form-switch mt-3">
        <input class="form-check-input" type="checkbox" id="demoData">
        <label class="form-check-label small" for="demoData">Also install clearly-marked <strong>demo content</strong> (sample shops, products, ads, businesses) — you can delete it later from Admin.</label>
      </div>
      <div id="adMsg" class="mt-3"></div>
      <button class="btn btn-ek mt-3" id="btn4">Create Admin <i class="fa-solid fa-user-shield ms-1"></i></button>
    </div>

    <div class="pane text-center" id="pane5">
      <div style="font-size:64px" class="text-success mb-2"><i class="fa-solid fa-circle-check"></i></div>
      <h4 class="fw-bold">Installation Complete! 🎉</h4>
      <p class="text-muted">Your lock file was created — the installer is now disabled for security.</p>
      <div class="d-flex gap-2 justify-content-center flex-wrap mt-4">
        <a class="btn btn-ek" href="../admin"><i class="fa-solid fa-gauge me-1"></i> Open Admin Panel</a>
        <a class="btn btn-outline-success rounded-3 px-4 fw-semibold" href="../"><i class="fa-solid fa-store me-1"></i> Visit Website</a>
      </div>
    </div>
  </div>
  <p class="text-center text-muted small mt-4">eKamalia v1.0 — PHP <?= PHP_VERSION ?> • <?= date('Y') ?></p>
</div>

<script>
const $ = id => document.getElementById(id);
const post = (doAct, data={}) => fetch('?do='+doAct, {method:'POST', headers:{'Content-Type':'application/x-www-form-urlencoded'}, body:new URLSearchParams(data)}).then(r=>r.json());
const dot = (n, cls) => { const d=$('dot'+n); d.classList.remove('active','done'); d.classList.add(cls); if(cls==='done') d.innerHTML='<i class="fa-solid fa-check"></i>'; };
const show = n => { document.querySelectorAll('.pane').forEach(p=>p.classList.remove('active')); $('pane'+n).classList.add('active'); };

/* step 1 */
fetch('?do=requirements').then(r=>r.json()).then(r=>{
  let html='';
  html += `<div class="check"><span>PHP ≥ 7.4 (you have ${r.php_version})</span><span class="${r.php_ok?'good':'bad'}">${r.php_ok?'OK':'FAIL'}</span></div>`;
  const exts={pdo_mysql:'PDO MySQL',gd:'GD (images/thumbnails)',mbstring:'Multibyte strings',curl:'cURL (SMTP/APIs)',openssl:'OpenSSL'};
  for(const [k,label] of Object.entries(exts)) html += `<div class="check"><span>${label}</span><span class="${r.extensions[k]?'good':'bad'}">${r.extensions[k]?'OK':'MISSING'}</span></div>`;
  for(const [d,ok] of Object.entries(r.dirs)) html += `<div class="check"><span><code>/${d}</code> writable</span><span class="${ok?'good':'bad'}">${ok?'OK':'NOT WRITABLE'}</span></div>`;
  $('reqBox').innerHTML = html;
  const allOk = r.php_ok && Object.values(r.extensions).every(Boolean) && Object.values(r.dirs).every(Boolean);
  $('btn1').disabled = !allOk;
  if(!allOk) $('reqBox').innerHTML += '<div class="alert alert-warning mt-2 mb-0 small">Fix the items above (chmod 755/775 or install extensions), then refresh this page.</div>';
});

$('btn1').onclick = ()=>{ dot(1,'done'); dot(2,'active'); show(2); };

/* step 2 */
$('btn2').onclick = async ()=>{
  $('dbMsg').innerHTML = '<span class="spinner-border spinner-border-sm text-success"></span> Testing…';
  const r = await post('test_db', {host:$('dbHost').value, name:$('dbName').value, user:$('dbUser').value, pass:$('dbPass').value});
  $('dbMsg').innerHTML = r.ok ? '<div class="alert alert-success py-2 mb-0"><i class="fa-solid fa-check me-1"></i>'+r.message+'</div>'
                              : '<div class="alert alert-danger py-2 mb-0">'+r.message+'</div>';
  if(r.ok){ dot(2,'done'); dot(3,'active'); setTimeout(()=>show(3), 500); }
};

/* step 3 */
$('btn3').onclick = async ()=>{
  const c = $('console'); c.style.display='block';
  c.innerHTML += '> Creating tables…\\n';
  const r = await post('migrate');
  c.innerHTML += (r.ok ? '✓ '+r.message : '✗ '+r.message) + '\\n';
  if(r.ok){ dot(3,'done'); dot(4,'active'); setTimeout(()=>show(4), 600); }
};

/* step 4 */
$('btn4').onclick = async ()=>{
  if($('adPass').value !== $('adPass2').value){ $('adMsg').innerHTML='<div class="alert alert-danger py-2 mb-0">Passwords do not match.</div>'; return; }
  $('adMsg').innerHTML = '<span class="spinner-border spinner-border-sm text-success"></span> Creating…';
  const r = await post('admin', {name:$('adName').value, email:$('adEmail').value, password:$('adPass').value, demo:$('demoData').checked?1:''});
  $('adMsg').innerHTML = r.ok ? '' : '<div class="alert alert-danger py-2 mb-0">'+r.message+'</div>';
  if(r.ok){ dot(4,'done'); dot(5,'active'); show(5); const f = await post('finish'); if(!f.ok) alert(f.message); }
};
</script>
</body>
</html>
