<?php
/* eKamalia config — generated by installer 2026-08-29T18:21:23+00:00 */
return [
    'db' => ['host' => 'localhost', 'name' => 'u107154643_kml', 'user' => 'u107154643_kml1', 'pass' => 'Pakistan7973117', 'charset' => 'utf8mb4'],
    'app' => ['url' => 'http://localhost:8080', 'key' => '042550f3c883df36861cc454cb1e422b22f1df566162fd3f6adba93bb1d722af', 'timezone' => 'Asia/Karachi', 'env' => 'production', 'version' => '1.0.0'],
];
