<?php
/**
 * eKamalia — Route table [METHOD, path, Controller@action]
 */
return [
    // home & general
    ['GET', '/', 'HomeController@index'],
    ['GET', '/explore-kamalia', 'HomeController@explore'],
    ['GET', '/cities', 'HomeController@cities'],
    ['POST', '/lang', 'HomeController@setLang'],
    ['GET', '/ad-click/{id}', 'HomeController@adClick'],
    ['GET', '/sitemap.php', 'PageController@sitemap'],
    ['GET', '/sitemap.xml', 'PageController@sitemap'],

    // auth
    ['GET', '/login', 'AuthController@showLogin'],
    ['POST', '/login', 'AuthController@login'],
    ['GET', '/register', 'AuthController@showRegister'],
    ['POST', '/register', 'AuthController@register'],
    ['GET', '/logout', 'AuthController@logout'],
    ['GET', '/verify-otp', 'AuthController@showVerifyOtp'],
    ['POST', '/verify-otp', 'AuthController@verifyOtp'],
    ['POST', '/resend-otp', 'AuthController@resendOtp'],
    ['GET', '/forgot-password', 'AuthController@showForgot'],
    ['POST', '/forgot-password', 'AuthController@forgot'],
    ['GET', '/reset-password', 'AuthController@showReset'],
    ['POST', '/reset-password', 'AuthController@reset'],

    // search & listings
    ['GET', '/search', 'SearchController@index'],
    ['POST', '/search/save', 'SocialController@saveSearch'],
    ['GET', '/category/{slug}', 'AdController@byCategory'],
    ['GET', '/products', 'ProductController@index'],
    ['GET', '/products/category/{slug}', 'ProductController@byCategory'],
    ['GET', '/product/{slug}', 'ProductController@show'],
    ['GET', '/deals', 'ProductController@deals'],
    ['GET', '/compare', 'ProductController@compare'],
    ['POST', '/compare/add', 'ProductController@compareAdd'],
    ['POST', '/compare/remove', 'ProductController@compareRemove'],

    // ads (classifieds)
    ['GET', '/ads', 'AdController@index'],
    ['GET', '/ad/{slug}', 'AdController@show'],
    ['GET', '/ads/create', 'AdController@create'],
    ['POST', '/ads/create', 'AdController@store'],
    ['GET', '/ads/{id}/edit', 'AdController@edit'],
    ['POST', '/ads/{id}/edit', 'AdController@update'],
    ['POST', '/ads/{id}/action', 'AdController@adAction'],
    ['GET', '/dashboard/my-ads', 'AdController@myAds'],

    // shops
    ['GET', '/shops', 'ShopController@index'],
    ['GET', '/shops/create', 'ShopController@create'],
    ['POST', '/shops/create', 'ShopController@store'],
    ['GET', '/shop/{slug}', 'ShopController@show'],
    ['POST', '/shops/{id}/chat', 'ShopController@startChat'],

    // businesses
    ['GET', '/businesses', 'BusinessController@index'],
    ['GET', '/businesses/create', 'BusinessController@create'],
    ['POST', '/businesses/create', 'BusinessController@store'],
    ['GET', '/business/{slug}', 'BusinessController@show'],

    // bijli (electricity)
    ['GET', '/bijli', 'BijliController@index'],
    ['POST', '/bijli/report', 'BijliController@report'],
    ['GET', '/api/bijli/reports', 'BijliController@reportsList'],

    // cart & checkout
    ['GET', '/cart', 'CartController@index'],
    ['POST', '/cart/add', 'CartController@add'],
    ['POST', '/cart/update', 'CartController@update'],
    ['POST', '/cart/remove', 'CartController@remove'],
    ['POST', '/cart/coupon', 'CartController@coupon'],
    ['GET', '/checkout', 'CheckoutController@index'],
    ['POST', '/checkout', 'CheckoutController@place'],
    ['GET', '/payment/{number}', 'CheckoutController@paymentPage'],
    ['POST', '/payment/{number}', 'CheckoutController@submitProof'],

    // orders
    ['GET', '/orders', 'OrderController@index'],
    ['GET', '/dashboard/orders', 'OrderController@index'],
    ['GET', '/dashboard/notifications', 'NotificationController@index'],
    ['GET', '/order/{number}', 'OrderController@show'],
    ['GET', '/track', 'OrderController@track'],
    ['POST', '/track', 'OrderController@trackResult'],
    ['POST', '/order/{number}/cancel', 'OrderController@cancel'],
    ['POST', '/order/{number}/refund', 'OrderController@refundRequest'],
    ['POST', '/order/{number}/received', 'OrderController@confirmReceived'],

    // chat
    ['GET', '/messages', 'ChatController@index'],
    ['GET', '/chat/{id}', 'ChatController@show'],
    ['POST', '/chat/{id}/send', 'ChatController@send'],
    ['GET', '/api/chat/{id}/poll', 'ChatController@poll'],
    ['POST', '/chat/{id}/block', 'ChatController@block'],
    ['POST', '/chat/{id}/report', 'ChatController@reportThread'],
    ['POST', '/chat/start', 'ChatController@start'],

    // social
    ['POST', '/api/wishlist/toggle', 'SocialController@toggleWishlist'],
    ['POST', '/api/like/toggle', 'SocialController@toggleLike'],
    ['POST', '/api/follow/toggle', 'SocialController@toggleFollow'],
    ['POST', '/comment', 'SocialController@commentStore'],
    ['POST', '/comment/delete', 'SocialController@commentDelete'],
    ['POST', '/review', 'SocialController@reviewStore'],
    ['POST', '/review/reply', 'SocialController@reviewReply'],
    ['POST', '/report', 'SocialController@report'],
    ['GET', '/api/recent/product/{id}', 'SocialController@recentProduct'],
    ['GET', '/api/recent/ad/{id}', 'SocialController@recentAd'],
    ['GET', '/api/recent/shop/{id}', 'SocialController@recentShop'],

    // notifications & misc api
    ['GET', '/notifications', 'NotificationController@index'],
    ['POST', '/notifications/read-all', 'NotificationController@readAll'],
    ['GET', '/api/notifications/poll', 'NotificationController@poll'],
    ['GET', '/api/search/suggest', 'ApiController@suggest'],
    ['GET', '/api/subcategories', 'ApiController@subcategories'],
    ['GET', '/categories', 'CategoryController@all'],
    ['GET', '/api/areas', 'ApiController@areas'],

    // CMS / content
    ['GET', '/page/{slug}', 'PageController@show'],
    ['GET', '/news', 'PageController@news'],
    ['GET', '/news/{slug}', 'PageController@newsShow'],
    ['GET', '/contact', 'PageController@contact'],
    ['POST', '/contact', 'PageController@contactSubmit'],

    // buyer dashboard
    ['GET', '/dashboard', 'DashboardController@index'],
    ['GET', '/dashboard/profile', 'DashboardController@profile'],
    ['POST', '/dashboard/profile', 'DashboardController@updateProfile'],
    ['GET', '/dashboard/security', 'DashboardController@security'],
    ['POST', '/dashboard/password', 'DashboardController@changePassword'],
    ['GET', '/dashboard/wishlist', 'DashboardController@wishlist'],
    ['GET', '/dashboard/following', 'DashboardController@following'],
    ['GET', '/dashboard/addresses', 'DashboardController@addresses'],
    ['POST', '/dashboard/addresses', 'DashboardController@addressStore'],
    ['POST', '/dashboard/addresses/{id}/delete', 'DashboardController@addressDelete'],
    ['GET', '/dashboard/activity', 'DashboardController@myComments'],
    ['POST', '/dashboard/delete-account', 'DashboardController@deleteAccount'],

    // seller dashboard
    ['GET', '/seller', 'SellerController@index'],
    ['GET', '/seller/products', 'SellerController@products'],
    ['GET', '/seller/products/create', 'SellerController@productForm'],
    ['POST', '/seller/products/save', 'SellerController@productSave'],
    ['GET', '/seller/products/{id}/edit', 'SellerController@productForm'],
    ['POST', '/seller/products/{id}/action', 'SellerController@productAction'],
    ['GET', '/seller/orders', 'SellerController@orders'],
    ['POST', '/seller/orders/status', 'SellerController@orderStatus'],
    ['GET', '/seller/coupons', 'SellerController@coupons'],
    ['POST', '/seller/coupons/save', 'SellerController@couponSave'],
    ['POST', '/seller/coupons/{id}/delete', 'SellerController@couponDelete'],
    ['GET', '/seller/reviews', 'SellerController@reviews'],
    ['GET', '/seller/analytics', 'SellerController@analytics'],
    ['GET', '/seller/settings', 'SellerController@settings'],
    ['GET', '/seller/customers', 'SellerController@customers'],
    ['GET', '/seller/inventory', 'SellerController@inventory'],
    ['POST', '/seller/inventory/update', 'SellerController@inventoryUpdate'],
    ['GET', '/seller/ads', 'SellerController@ads'],
    ['GET', '/seller/payments', 'SellerController@payments'],
    ['GET', '/seller/delivery', 'SellerController@delivery'],
    ['POST', '/seller/settings', 'SellerController@settingsSave'],

    // POS
    ['GET', '/pos/request', 'PosController@requestPage'],
    ['POST', '/pos/request', 'PosController@requestSubmit'],
    ['GET', '/pos', 'PosController@index'],
    ['POST', '/pos/checkout', 'PosController@checkout'],
    ['POST', '/pos/holds/{id}/resume', 'PosController@resumeHold'],
    ['GET', '/pos/dashboard', 'PosController@dashboard'],
    ['GET', '/pos/invoices', 'PosController@invoices'],
    ['GET', '/pos/invoice/{id}', 'PosController@invoice'],
    ['GET', '/pos/invoice/{id}/print', 'PosController@invoicePrint'],
    ['GET', '/pos/returns', 'PosController@returns'],
    ['POST', '/pos/returns/find', 'PosController@returnFind'],
    ['POST', '/pos/returns/process', 'PosController@returnProcess'],
    ['GET', '/pos/purchases', 'PosController@purchases'],
    ['POST', '/pos/purchases/save', 'PosController@purchaseSave'],
    ['GET', '/pos/customers', 'PosController@customers'],
    ['POST', '/pos/customers/save', 'PosController@customerSave'],
    ['POST', '/pos/customers/{id}/delete', 'PosController@customerDelete'],
    ['GET', '/pos/suppliers', 'PosController@suppliers'],
    ['POST', '/pos/suppliers/save', 'PosController@supplierSave'],
    ['GET', '/pos/expenses', 'PosController@expenses'],
    ['POST', '/pos/expenses/save', 'PosController@expenseSave'],
    ['POST', '/pos/expenses/{id}/delete', 'PosController@expenseDelete'],
    ['GET', '/pos/inventory', 'PosController@inventory'],
    ['POST', '/pos/inventory/adjust', 'PosController@adjustStock'],
    ['GET', '/pos/reports', 'PosController@reports'],
    ['GET', '/pos/reports/export', 'PosController@reportExport'],
    ['GET', '/pos/staff', 'PosController@staff'],
    ['POST', '/pos/staff/add', 'PosController@staffAdd'],
    ['POST', '/pos/staff/update', 'PosController@staffUpdate'],

    // ================= ADMIN =================
    ['GET', '/admin', 'Admin\AdminController@dashboard'],
    ['GET', '/admin/audit', 'Admin\AdminController@auditLogs'],
    ['GET', '/admin/health', 'Admin\AdminController@health'],
    ['GET', '/admin/backups', 'Admin\AdminController@backups'],
    ['POST', '/admin/backups', 'Admin\AdminController@backups'],
    ['GET', '/admin/backups/{name}/download', 'Admin\AdminController@backupDownload'],
    ['POST', '/admin/backups/{name}/delete', 'Admin\AdminController@backupDelete'],

    ['GET', '/admin/users', 'Admin\UsersController@index'],
    ['GET', '/admin/users/{id}', 'Admin\UsersController@show'],
    ['POST', '/admin/users/{id}/update', 'Admin\UsersController@update'],

    ['GET', '/admin/shops', 'Admin\ShopsController@index'],
    ['POST', '/admin/shops/{id}/update', 'Admin\ShopsController@update'],
    ['GET', '/admin/pos-requests', 'Admin\ShopsController@posRequests'],
    ['POST', '/admin/pos-requests/{id}/update', 'Admin\ShopsController@posRequestUpdate'],
    ['GET', '/admin/packages', 'Admin\ShopsController@packages'],
    ['POST', '/admin/packages/save', 'Admin\ShopsController@packages'],
    ['POST', '/admin/pos-packages/save', 'Admin\ShopsController@posPackages'],
    ['POST', '/admin/packages/{id}/delete', 'Admin\ShopsController@packageDelete'],
    ['GET', '/admin/promotions', 'Admin\ShopsController@promotions'],
    ['POST', '/admin/promotions/{id}/update', 'Admin\ShopsController@promotionUpdate'],

    ['GET', '/admin/products', 'Admin\CatalogController@products'],
    ['POST', '/admin/products/{id}/update', 'Admin\CatalogController@productUpdate'],
    ['GET', '/admin/ads', 'Admin\CatalogController@ads'],
    ['POST', '/admin/ads/{id}/update', 'Admin\CatalogController@adUpdate'],
    ['GET', '/admin/categories', 'Admin\CatalogController@categories'],
    ['POST', '/admin/categories/save', 'Admin\CatalogController@categories'],
    ['POST', '/admin/categories/{id}/delete', 'Admin\CatalogController@categoryDelete'],
    ['POST', '/admin/brands/save', 'Admin\CatalogController@brands'],
    ['POST', '/admin/brands/{id}/delete', 'Admin\CatalogController@brandDelete'],

    ['GET', '/admin/orders', 'Admin\OrdersController@index'],
    ['GET', '/admin/orders/{id}', 'Admin\OrdersController@show'],
    ['POST', '/admin/orders/status', 'Admin\OrdersController@status'],
    ['GET', '/admin/payments', 'Admin\OrdersController@payments'],
    ['POST', '/admin/payments/{id}/update', 'Admin\OrdersController@paymentVerify'],
    ['GET', '/admin/banks', 'Admin\OrdersController@banks'],
    ['POST', '/admin/banks/save', 'Admin\OrdersController@banks'],
    ['POST', '/admin/banks/{id}/delete', 'Admin\OrdersController@bankDelete'],
    ['GET', '/admin/analytics', 'Admin\OrdersController@analytics'],

    ['GET', '/admin/sliders', 'Admin\ContentController@sliders'],
    ['POST', '/admin/sliders/save', 'Admin\ContentController@sliders'],
    ['POST', '/admin/sliders/{id}/delete', 'Admin\ContentController@sliderDelete'],
    ['GET', '/admin/marquee', 'Admin\ContentController@marquees'],
    ['POST', '/admin/marquee/save', 'Admin\ContentController@marquees'],
    ['POST', '/admin/marquee/{id}/delete', 'Admin\ContentController@marqueeDelete'],
    ['GET', '/admin/advertisements', 'Admin\ContentController@advertisements'],
    ['POST', '/admin/advertisements/save', 'Admin\ContentController@advertisements'],
    ['POST', '/admin/advertisements/{id}/delete', 'Admin\ContentController@advertisementDelete'],
    ['GET', '/admin/pages', 'Admin\ContentController@pages'],
    ['POST', '/admin/pages/save', 'Admin\ContentController@pages'],
    ['GET', '/admin/pages/{id}/edit', 'Admin\ContentController@pageEdit'],
    ['POST', '/admin/pages/{id}/delete', 'Admin\ContentController@pageDelete'],
    ['GET', '/admin/news', 'Admin\ContentController@news'],
    ['POST', '/admin/news/save', 'Admin\ContentController@news'],
    ['POST', '/admin/news/{id}/delete', 'Admin\ContentController@newsDelete'],
    ['GET', '/admin/testimonials', 'Admin\ContentController@testimonials'],
    ['POST', '/admin/testimonials/save', 'Admin\ContentController@testimonials'],
    ['POST', '/admin/testimonials/{id}/delete', 'Admin\ContentController@testimonialDelete'],
    ['GET', '/admin/homepage', 'Admin\ContentController@homepage'],
    ['POST', '/admin/homepage', 'Admin\ContentController@homepage'],
    ['GET', '/admin/businesses', 'Admin\ContentController@businesses'],
    ['POST', '/admin/businesses/{id}/update', 'Admin\ContentController@businessUpdate'],

    // bijli admin
    ['GET', '/admin/bijli', 'Admin\ContentController@bijli'],
    ['POST', '/admin/bijli/feeder/save', 'Admin\ContentController@feederSave'],
    ['POST', '/admin/bijli/feeder/{id}/delete', 'Admin\ContentController@feederDelete'],
    ['POST', '/admin/bijli/feeder/update-status', 'Admin\ContentController@feederUpdatePost'],
    ['POST', '/admin/bijli/reports/{id}/update', 'Admin\ContentController@feederReportUpdate'],

    // moderation
    ['GET', '/admin/reviews', 'Admin\ModerationController@reviews'],
    ['POST', '/admin/reviews/{id}/update', 'Admin\ModerationController@reviewUpdate'],
    ['GET', '/admin/comments', 'Admin\ModerationController@comments'],
    ['POST', '/admin/comments/{id}/update', 'Admin\ModerationController@commentUpdate'],
    ['GET', '/admin/reports', 'Admin\ModerationController@reports'],
    ['POST', '/admin/reports/{id}/update', 'Admin\ModerationController@reportUpdate'],
    ['GET', '/admin/inbox', 'Admin\ModerationController@inbox'],
    ['POST', '/admin/inbox/{id}/update', 'Admin\ModerationController@inboxUpdate'],

    // settings
    ['GET', '/admin/settings', 'Admin\ModerationController@settings'],
    ['POST', '/admin/settings', 'Admin\ModerationController@settings'],
    ['POST', '/admin/settings/test-email', 'Admin\ModerationController@testEmail'],
];
